#!/bin/bash

mkdir "$1"

cd "$1"

mkdir css
mkdir js

touch css/style.css
touch js/index.js

cat <<EOT >> index.html
<!doctype html>
<html>
  <head>
    <title></title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="style.css">
    <script type="text/javascript" src="js/index.js"></script>
  </head>
  <body>

  </body>
</html>
EOT

cat <<EOT >> jsconfig.json
{
  "compilerOptions": {
    "module": "es6",
    "target": "es6"
  },
  "exclude": ["node_modules"]
}
EOT

git init
