#!/bin/bash

npx create-react-app "$1"

cd "$1"

cat <<EOT >> jsconfig.json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2017",
    "allowSyntheticDefaultImports": true,
    "noEmit": true,
    "checkJs": true,
    "jsx": "react",
    "lib": [ "dom", "es2017" ]
  }
}
EOT

git init
